# Generated by Django 2.2.12 on 2021-03-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
